# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginreg_app', '0002_auto_20170128_2004'),
        ('courses_app', '0002_auto_20170126_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(to='loginreg_app.User'),
        ),
    ]
